version: '3.3'
services: 
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    ports: 
      - 27017:27017
    volumes:
      - mongodb:/data/db
  node:
    depends_on: 
      - mongodb
    restart: unless-stopped
    build: .
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment: 
      - DB_URL=$DB_URL
      - PORT=$PORT
      - APP_URL=$APP_URL
      - API_URL=$API_URL
      - NODE_ENV=$NODE_ENV
    stdin_open: true
    tty: true
volumes: 
  mongodb: